### ISSUE TITLE
"missing terminating newline" error when creates config in k8s

### ISSUE THREAD

**Issue by eskornev** [prometheus/statsd_exporter#102]
Hello!
There is situation when statsd_exporter won't start if there is no newline in config file.
We are using kubernetes 1.6 and unfortunately it creates config files from configmaps 
with no newline at the end of file... Is it possible to eliminate this restriction?

**Comment by eskornev** [comment]
Just builded version 0.4.0 from source and stumbled upon yaml config file - it seems like statd exporter dont like * in the beginning of mapping match string. This config fails:

mappings:
- match: *.signup.*.*
  labels:
    name: "signup_events_total"
    provider: "$2"
    outcome: "$3"
    job: "${1}_server"

Error is: FATA[0000] Error loading config:yaml: line 1: did not find expected alphabetic or numeric character  source="main.go:193"

But this config is ok:
mappings:
- match: abcabc.*.signup.*.*
  labels:
    name: "signup_events_total"
    provider: "$2"
    outcome: "$3"
    job: "${1}_server"

**Comment by matthiasr** [comment]
I think this is a limitation of the YAML format – it tries to parse `*something` as an alias to some anchor defined elsewhere, but `.signup` is not a valid anchor either. To fix this, you need to enclose the problematic string in quotes, like

```yaml
mappings:
- match: "*.signup.*.*"
  labels:
    name: "signup_events_total"
    provider: "$2"
    outcome: "$3"
    job: "${1}_server"
```

**Comment by matthiasr** [comment]
Oh, I think there is the problem:

> builded version 0.4.0 from source and stumbled upon yaml config file

0.4.0 does not support the YAML config yet. I'm sorry about the confusion, basically everything about the configuration format has changed since the last release, so the README you see on the project page is not very helpful if you are using 0.4.0.

There will be a release soon (#100), until then please try building from master. Keep in mind that the config format will change once more (#101) but this will be very easy to adapt to.
