### ISSUE TITLE
followup question about statsd_exporter vs. pushgateway

### ISSUE THREAD

**Issue by Arnold1** [prometheus/statsd_exporter#113]
Hi @matthiasr,
I still have a follow-up question. I plan to use short living batch jobs, long living batch jobs (they will be converted to streaming jobs over time) and spark streaming jobs. Can't I not just simply push all metrics to the pushgateway rather than using statsd_exporter at all and prometheus scrapes the metrics from there? What speaks against it?
For example: Imagine statsd_exporter restarts, all metrics get lost?
Thanks,
Arnold

**Comment by beorn7** [comment]
I suggest to check your use cases against https://prometheus.io/docs/practices/pushing/ .

On a more general note, it makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
