### ISSUE TITLE
How to improve availability?

### ISSUE THREAD

**Issue by igorvpcleao** [prometheus/statsd_exporter#116]
How can I scale stastd_exporter in order to improve availability?

I was considering to have a load balancer pointing to two stastd_exporter instances. Then I would query for the sum of every instance, given a certain metric. This approach works fine with counters, but fails with gauges.

Would you guys have a suggestion?

**Comment by matthiasr** [comment]
The approach that I have taken is to deploy the statsd exporter alongside every _application_ instance, with their lifecycles tied together as much as possible – concretely, running statsd in the same Kubernetes [pod](https://kubernetes.io/docs/concepts/workloads/pods/pod/#what-is-a-pod). That way, there is no central exporter that could fail.

This has additional benefits: you get per-instance metrics very easily. By using local networking only, and spreading the statsd load you avoid missing events due to dropped packets. And by tying the lifecycles together you avoid stale metrics due to metric name changes.

If you prefer to run multiple central exporters, then instead of a load balancer I would try to duplicate the stats updates using the [statsd proxy config](https://github.com/etsy/statsd/blob/master/exampleProxyConfig.js), but then you have the same problem again on another layer.

Aggregating gauges is possible, but depends on the nature of the gauge. I tend to take the `max without(instance) (…)` because that gives me the worst case for the metrics where I've needed this, but for others it might be more appropriate to use the average or minimum.

I hope this helps! I'm going to close this issue, since there is no proposed change to or problem in the exporter itself, and it's better if we discuss usage questions like this on the [mailing lists](https://prometheus.io/community/).
