### ISSUE TITLE
The scaling of timer data should be unified, or (preferably) user specified.

### ISSUE THREAD

**Issue by SpencerMalone** [prometheus/statsd_exporter#177]
https://github.com/prometheus/statsd_exporter/blob/2d35b097ae242e0a15317d7dfb5f8be0f199567e/exporter.go#L407 Scales histograms by 1000, but the same isn't applied to summaries? In reality, I prefer that either no scaling occurs, or that we have a yaml entry to allow us to specify scaling of timer data. Short term though, just unification of summary and histograms would be very nice, as it can come as quite a surprise when you switch data between the two while setting up your mappings.

**Comment by matthiasr** [comment]
Oh that is indeed a bug. The summary observation should also be scaled. Could you submit a PR for that?

I would rather not make this configurable – in Prometheus metrics, there is a strong preference for scaling to seconds. And since everything is a float, there is really no reason not to use them.
