### ISSUE TITLE
Large amounts of metrics lead to data loss

### ISSUE THREAD

**Issue by idling11** [prometheus/statsd_exporter#185]
HI, all:
Recently, I was troubled by a problem. I collect large amounts of  metrics from  flink ,  when data go through  statsd -->  statsd_export --> prometheus  and show data out in  grafana.   But i notice  that  the Summation of some  metrics is wrong and   I guess the data is missing.  Is there any possibility of data loss on this pipeline?  (The cpu usage of  statsd and statsd_export is high)

**Comment by matthiasr** [comment]
Yes, that is very likely, since the flink -> statsd and statsd -> exporter links are all [using UDP](https://jvns.ca/blog/2016/08/24/find-out-where-youre-dropping-packets/). Neither statsd nor the exporter will be able to handle this use case.

I would *strongly* suggest that you investigate exposing Prometheus metrics directly from flink, this [is](https://www.slideshare.net/FlinkForward/flink-forward-berlin-2018-maximilian-bode-monitoring-flink-with-prometheus) [possible](https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/metrics.html#prometheus-orgapacheflinkmetricsprometheusprometheusreporter).

Since there is nothing we can really do about it, and there is an alternative available, I'm going to close this issue. You can also use the [community mailing lists](https://prometheus.io/community) for questions on how to use the various integrations.
