### ISSUE TITLE
where does statsd_exporter store metrics data

### ISSUE THREAD

**Issue by idling11** [prometheus/statsd_exporter#188]
Hi all:
I try to use statsd_exporter and prometheus recently.  After a few days , I found that  the  "Scrape Duration" of  prometheus  increased  all the way  and the value almost  beyond  the  "scrape_timeout" of   prometheus.  So, I  want  to know  that  where  statsd_export store  the metrics which it  received  before  prometheus pulling?  Does it works if  I  reduce  the value  of  "scrape_interval" ?

**Comment by matthiasr** [comment]
The exporter only keeps the metrics it has collected in memory. By default, it does not expire any metrics, so if you have a set of metrics/labels that keeps changing over time, it will keep accumulating metrics.

The _best_ way to deal with this is to tie the exporter lifecycle to the application – that is, run it as a sidecar alongside each application instance, and deploy / restart them together. This also avoids all kinds of issues with incompatible label sets. Additionally, you get per-instance metrics for free, using Prometheus' discovery and handling, instead of having to submit "this metric came from node X" as part of the metric (in fact, if your application does send this, drop it in the mapping config).

If this is not possible at all, the [upcoming release](https://github.com/prometheus/statsd_exporter/releases/tag/v0.9.0-rc3) allows timing out metrics after a while.

**Comment by matthiasr** [comment]
PS: it's better to ask usage questions on the [mailing lists](https://prometheus.io/community/), more people can answer them there.
