### ISSUE TITLE
statsd_exporter as permanent solution?

### ISSUE THREAD

**Issue by john-vellozzi-avalara** [prometheus/statsd_exporter#269]
We're trying to aggregate stats from AWS Lambda functions and scrape them with Prometheus.  It sounds like statsd_exporter is the way to do it.

Can you comment on this excerpt from the statsd_exporter README.md?
"We recommend this only as an intermediate solution and recommend switching to native Prometheus instrumentation in the long term."

It seems like native Prometheus instrumentation isn't possible for us.  Is there really a reason we shouldn't use statsd_exporter indefinitely?  If so, what's the issue, and what would you recommend?

**Comment by matthiasr** [comment]
One problem with using the statsd exporter is that it forces you to loop through a somewhat different metric model. The way statsd treats "events", and how the exporter translates them into Prometheus metrics, is not without translation losses.

Another problem is that you don't really know if the event "made it" to your monitoring, especially if you are using the UDP protocol. You will also lose metrics whenever statsd exporter is unavailable; you can run more than one but now you have to aggregate metrics _again_ and semantics around that can be vague.

A more prometheus-native solution to this is [prom-aggregation-gateway](https://github.com/weaveworks/prom-aggregation-gateway).

Fundamentally, the issue as I see it is that Prometheus does not work well with ephemeral "functions" since it expects to have something somewhat-stable that it can scrape. In the FaaS context, that would mean the _service_ would need to provide a framework for function invocations to emit events/metrics that are then aggregated in the runtime and can be scraped by Prometheus. Unfortunately, in the case of AWS Lambda, that is CloudWatch which only gives you reliable metrics several minutes later.

So options that I see is:

* keep using `statsd_exporter`. No one can stop you.
* use prom-aggregation-gateway. You'll have the same reliability / aggregation issues, but not the loop through a different metric model
* ask your AWS account manager for a way to get up-to-date metrics from Lambda reliably
* maybe there is some Lambda-native metric aggregation system out there that I don't know about?

**Comment by brian-brazil** [comment]
> maybe there is some Lambda-native metric aggregation system out there that I don't know about?

That'd be CloudWatch.
