### ISSUE TITLE
docker tag without leading v

### ISSUE THREAD

**Issue by clux** [prometheus/statsd_exporter#293]
See [statsd-exporter/tags](https://hub.docker.com/r/prom/statsd-exporter/tags).

Out of all the projects on the [front page on docker hub](https://hub.docker.com/explore/), almost no one is prefixing tags with a leading `v`. Consistency wise, is it possible to tag without it?

This might be a little nitpick, but it would be nice to be able to parse tags that are masquerading as semver, as semver. Pretty much everything provides some valid semver tags (even if they are using semver specifiers dash separated). It's not a big problem, just trying to lock down version pinning so that we don't rely on floating tags everywhere, and semver enforcement is a nice way of doing that.

**Comment by matthiasr** [comment]
That's a good question, I don't have a preference either way. However, statsd exporter blindly consumes the [common build tooling](https://github.com/prometheus/promu) of the whole Prometheus project, and should be consistent with that (more than it should be consistent with the rest of the world).

Can you bring this up on the [prometheus-developers mailing list](https://groups.google.com/forum/#!forum/prometheus-developers) for a wider discussion? I'm going to close the issue here since I don't want to do this as a localized change, and any "upstream" change will be picked up automatically.

**Comment by clux** [comment]
Nah, that makes complete sense. Going to just stop trying to fight this inconsistency.
