### ISSUE TITLE
FR: wildcards allowed in --statsd.mapping-config for multiple files

### ISSUE THREAD

**Issue by sevagh** [prometheus/statsd_exporter#304]
Hello,

It would be nice if we could specify multiple mapping files, either by repeating the flag, or using wildcards (the way Prometheus works):

```
$ statsd_exporter --statsd.mapping-config=/opt/statsd-exporter/mapping_confs/*.conf
```

**Comment by matthiasr** [comment]
Hmm, this adds a lot of new edge cases. The mappings within one file are interpreted in order; how would that order work between multiple files? What happens if defaults are specified in multiple files? What if these conflict, say, one file sets `glob_disable_ordering: false` while the other does not?

Can you go into more detail about the use case, and how you would expect these edge cases to be handled?

**Comment by sevagh** [comment]
I hadn't really considered the implementation complexity. My thought process is convenience for self-service - for example Prometheus rules yml files, you can maintain separate service rules in "service_a.yml", "service_b.yml" files.

I would like to do the same, where "service_a_mappings.conf" and "service_b_mappings.conf".

If it's as complicated as you say, I can probably live with maintaining a single file, or maybe add some basic Jinja templating to split it myself.

**Comment by sevagh** [comment]
Why close this so abruptly? Is it such a bad idea?

**Comment by matthiasr** [comment]
Ah sorry, I should have written down the rationale … as you said, there is a lot of complexity in the implementation, and you have a working solution (generating the consolidated file according to the semantics _you_ need). In light of that, I would rather not take up the complexity into the exporter itself.
