### ISSUE TITLE
[HELP] Database for Exporter - Do we need it?

### ISSUE THREAD

**Issue by Andreluizfc** [prometheus/statsd_exporter#417]
Hi,

I am running the exporter in a K8s Deployment. The problem I'm facing is the Metrics get reset every time my Container restarts.

Does my Exporter Service need to have a database to Store the Metrics?

Isn't Prometheus's job to store the metrics and Exporter work only as a Bridge?

**Comment by matthiasr** [comment]
Yes, Prometheus stores the metrics. For a specific (counter) time series the reset is handled by the `rate()` and `increase()` query functions. So typically you would graph `rate(some_counter_total[5m])` rather than the raw counter.

However, neither Prometheus nor the exporter can know the total set of possible metrics; for infrequently reported counters this can lead to some gaps. In that case, the best course of action is to directly instrument your app, and to initialize (increment by 0) all the metrics/label combinations you know will be there at launch.

Please direct general Prometheus related questions to the appropriate [community channels](https://prometheus.io/community).
