### ISSUE TITLE
Submitting statsd.distribution's with `_count` can be dangerous

### ISSUE THREAD

**Issue by diranged** [prometheus/statsd_exporter#456]
Similar to https://github.com/prometheus/statsd_exporter/issues/186, we have found another way to poison the `/metrics` endpoint. As we've started migrating to using the exporter, we found this codepath can break the statsd-exporter in a new fun way:

```python
stats.distribution('cache_miss', tags=[f'caller:{self._caller_tag}'])
stats.distribution('cache_miss_count', len(redis_cache_miss_keys),tags=[f'caller:{self._caller_tag}'])
```

The problem is that the first call creates `cache_miss` and also `cache_miss_sum` and `cache_miss_count`. Then the second call hits statsd-exporter and it tries to create `cache_miss_count` ... but that conflicts with the previously auto-generated metric:

```
$ curl localhost:9090/metrics -v 
*   Trying 127.0.0.1:9090...
* Connected to localhost (127.0.0.1) port 9090 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:9090
> User-Agent: curl/7.79.1
> Accept: */*
> 
Handling connection for 9090
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 03 Aug 2022 18:28:41 GMT
< Content-Length: 192
< 
An error has occurred while serving metrics:

collected metric named "cache_miss_count" collides with previously collected summary named "cache_miss"
* Connection #0 to host localhost left intact
```

The question is, what is the right way to deal with this? For the time being we're putting in a mapping config to rename any metric called `_count` or `_sum` to `_total`... but we don't like renaming our users metrics. There are plenty of valid metric names where `_count` makes sense... and we are talking about millions of lines of code in this one application, so it's not trivial to go and "fix" each place where we might have a collision.

Any thoughts on what should happen here?

**Comment by matthiasr** [comment]
Hmm, this is a tricky one, I am not sure we can solve this in a general way.

In your example, it looks like there are two things being recorded: how many cache misses there were, and how many keys were missed. In Prometheus summaries and histograms, observing only the latter also gets you the former (as the `_count` metric). So in this particular case the best thing would be to drop the redundant `cache_miss` events on the floor. The exporter cannot do that automatically because it cannot foresee the future, and it cannot know the semantics of these.

I wonder what it does to make `cache_miss` a distribution – won't the value always be 1?

**Comment by matthiasr** [comment]
At the least, the exporter should probably reject the second event because it will conflict. That is, for any metric where the name ends in `_count` or `_sum`, reject if the base name already exists as a summary or histogram.

I am open to suggestions on handling this more intelligently but we need to be careful not to make any assumptions about other use cases.

**Comment by matthiasr** [comment]
For your particular case, can you get a list of metric names from statsd and detect collisions from that? You may have to make a judgment call on each of them to decide which one is redundant, if any, unless you have strong conventions that would allow you to, say, drop any distribution events that do _not_ end in, say `_(count|time|size)` because they would all be redundant in the same way.

**Comment by diranged** [comment]
> The exporter cannot do that automatically because it cannot foresee the future, and it cannot know the semantics of these.

As you mentioned - I think the exporter shoudl drop the second event. Basically I think any new metric that can break the `/metrics` endpoint should be rejected and errors should be thrown in the logs. You are right, the mistake is in our client code .. however, breaking the statsd-exporter has lots of potentially serious consequences (broken autoscaling, etc), so we want to _never_ do that.

**Comment by matthiasr** [comment]
Indeed – #461 will hopefully fix that
