### ISSUE TITLE
Single tag in metric reporting NaN

### ISSUE THREAD

**Issue by devblueray** [prometheus/statsd_exporter#488]
Hey all, ran into a strange issue this morning.  Using the statsd exporter and ended up with one metric using one tag just started reporting NaN.  Every other tag with that metric continued to work.  The strangeness came when the issue was resolved by restarting the statd exporter pod.  Anyone know what happened and how I can prevent it going forward?

**Comment by matthiasr** [comment]
It's hard to say without knowing what statsd events led to this and the mapping configuration. One thing I can imagine is that it somehow read the value or the sampling factor as zero, but without the raw event this is impossible to track down.

It makes sense that it would stay broken because in floating point math, `NaN + anything = NaN`

If this keeps happening, please check the values of the sample error metrics. Also run the exporter with debug logging enabled to collect more information. Note that this can produce a lot of output.

Since we don't have anything to go on right now, I'm going to close this issue. If it happens again, please reopen it and post the mapping configuration and the log lines for the events that feed the affected tag. Thank you!

**Comment by devblueray** [comment]
Thanks for the reply.  Perhaps I misunderstood then.  I thought the statsd exporter didn't calculate between 2 values but just reported what it received in real time and let prometheus do the calculation.  I was seeing NaN on the /metrics page of statsd exporter.

**Comment by matthiasr** [comment]
It depends on the statsd event type. For gauges, yes, only the last value is retained. For counters, the exporter adds them all up. Histograms are more complicated, but at least the sum metric is also added up.
