### ISSUE TITLE
feature request: persistence

### ISSUE THREAD

**Issue by hryamzik** [prometheus/statsd_exporter#49]
This exporter seem to be loosing metrics on restarts, can we get persistence for them as it's done in the push gateway?

**Comment by SuperQ** [comment]
This is not generally necessary or desired.  Can you explain your use case?

**Comment by hryamzik** [comment]
All the metrics should be initialised, that's one the the prometheus requirements. Once you restart your statsd gateway it looses all the metrics. So if you report some metric rarely you'll end up missing it for a while. Of cource you can force your code to report current states on gateway restarts or even implement a separate initialiser but persistence seem to be the best solutions here.

**Comment by fungusakafungus** [comment]
pushgateway has its [`-persistence.file`](https://github.com/prometheus/pushgateway#run-it)

**Comment by hryamzik** [comment]
@fungusakafungus indeed but statsd_exporter doesn't have this option.

**Comment by matthiasr** [comment]
StatsD (at least the original one, it's the only one I've every used in anger) doesn't have persistence either.

I can see that there are some use cases where this might be useful, but I really would like to keep this complexity away from this exporter. The pushgateway serves a somewhat different use case than this exporter, and also does not have the additional complexity of translating from very different metrics models. It is also the preferred integration point for rarely reported metrics (i.e. from batch jobs).

For long-running jobs, in the Prometheus native world, it is the job's responsibility to "remember" the metrics. With the exporter, I would again recommend to couple its lifecycle to that of the application, so that you get in essence the same effect.

All in all, I'm afraid this is a feature that I'll just have to say No to.

**Comment by gchhablani** [comment]
Can you please suggest a way to persist the metrics through a container restart?
