### ISSUE TITLE
Unable to disable the udp port listening

### ISSUE THREAD

**Issue by GSokol** [prometheus/statsd_exporter#505]
When I trying to add `--statsd.listen-udp=''`, I receiving an error message:
```
ts=2023-06-12T06:32:01.373Z caller=main.go:293 level=info msg="Starting StatsD -> Prometheus Exporter" version="(version=0.24.0, branch=HEAD, revision=e91ce201d50556b1ccf21c484c4b93c3b10a3442)"
ts=2023-06-12T06:32:01.373Z caller=main.go:294 level=info msg="Build context" context="(go=go1.19.9, platform=linux/amd64, user=root@7a17abca8ba6, date=20230602-08:00:37, tags=netgo static_build)"
ts=2023-06-12T06:32:01.374Z caller=main.go:343 level=info msg="Accepting StatsD Traffic" udp='' tcp="\":8125\"" unixgram=
ts=2023-06-12T06:32:01.374Z caller=main.go:344 level=info msg="Accepting Prometheus Requests" addr=:9102
ts=2023-06-12T06:32:01.374Z caller=main.go:354 level=error msg="invalid UDP listen address" address='' error="bad StatsD listening address: ''"
```

**Comment by matthiasr** [comment]
This is a shell parsing/quoting issue: From the error, I can see that the exporter got the literal string `''` (two single quotes) as the listen address.

On a command line, the shell would parse the quotes, and turn `./statsd-exporter --statsd.listen-udp=''` into the argument list `["./statsd-exporter", "--statsd.listen-udp"]`. It seems that you have used this flag in a context what does no such parsing; this is typically the case when you specify the arguments as an array rather than the whole command as a string. Dockerfiles, docker-compose, Kubernetes, and many other contexts work that way.

Try passing `--statsd.listen-udp=` instead (no empty quotes), that will work in either case.

**Comment by matthiasr** [comment]
Also note that your TCP listener seems to have too many quotes as well.
