### ISSUE TITLE
statsd-exporter:v0.17.0 Docker image CVE Report.

### ISSUE THREAD

**Issue by ns-pmistry** [prometheus/statsd_exporter#585]
We found vulnerabilities in the statsd-exporter-v0.17.0 docker file. 
The performed Jfrog docker scans. 
[statsd-exporter-v0.17.0-CVE-report.txt](https://github.com/user-attachments/files/17243204/statsd-exporter-v0.17.0-CVE-report.txt)

**Comment by matthiasr** [comment]
0.17 is [more than four years old](https://github.com/prometheus/statsd_exporter/releases/tag/v0.17.0). This is fixed in subsequent versions. Please [do not report plain CVE scan results](https://prometheus.io/docs/operating/security/#automated-security-scanners) and _especially_ not on ancient versions.
