### ISSUE TITLE
Metric expiry/reset

### ISSUE THREAD

**Issue by lobeck** [prometheus/statsd_exporter#83]
statsd will automatically reset counters when publishing to graphite and i'm looking for a similar feature in the exporter too. Did i miss the settings for this or isn't this available?

Currently we use counters which get reset on every publish, so we can use that values to detect inactivity or outages (when the metric is no longer updated). Technically it's a gauge with automatic expiry when not updated for a while.

Is there an option to expire or reset after a certain amount of time? Otherwise we'll need to look into the full prometheus instrumentation migration which was actually planned for later this year.

**Comment by SuperQ** [comment]
Counters which get reset on every publish seem more like increment events.  The statsd_exporter should be able to take these events and turn them into "real" Prometheus counters.

You could simulate the lack of updates with Prometheus by using the `changes()` function.  

```
ALERT MetricNotUpdating
  IF changes(counter_metric_total[10m]) < 1
```

This would alert if no updates have been published to Prometheus via the cumulative counter in the last 10 minutes.

**Comment by tonidas** [comment]
What about gauges @SuperQ? It would be nice if the exporter reset its metrics to prevent old data being considered new.

**Comment by SuperQ** [comment]
It is not possible to expire gauges as the statsd protocol does not have "this is expired" message that I'm aware of.  Gauges represent "the last sampled value", so they're always "stale" depending on the timeframe of the value.  It is not possible to correctly expire them without an explicit method in the statsd protocol.

**Comment by tonidas** [comment]
@SuperQ Thanks for the reply.

I'm considering to reboot the container, periodically, to detect the absence of new metrics, as they are not persisted.

**Comment by SuperQ** [comment]
It would be good to tie the lifecycle of the statsd_exporter to the lifecycle of the app writing to it.  This way you get consistency with the metrics exported by the application writing to the exporter.

**Comment by clayg** [comment]
FWIW the way that gauges are reported in otel's statsd receiver seems to be related to the collection/flush interval

If the gauge metric (with those same specific labels) doesn't get re-submitted during the next collection/aggregation interval it won't be reported.

This turns out to be exactly how I would like a labeled gauge to work, i.e.

"this pid is using x memory"

and then I can sum all my workers memory, and if I restart them - I don't want my statsd collector to keep reporting that old pid is "still using" 10M of memory forever until the end of time or when I restart the statsd exporter process.

FWIW the "memory per pid" example is somewhat contrived; with a more complex set of labels it's just not reasonable for the application to have to *explicitly* reset the gauge to 0 for every combination of possible labels.  The original/reference implementation seemed to understand this implication for gauges and supports the option:

>   deleteGauges:     don't send values to graphite for inactive gauges, as opposed to sending the previous value [default: false]

https://github.com/statsd/statsd/blob/master/exampleConfig.js#L64

I assume the "default" is false for backwards compatibility for "simple" use of gauges were they wanted to support an edge triggered report interval - rather than the expected/normal "keep-alive style" gauge metric emission.

> It would be good to tie the lifecycle of the statsd_exporter to the lifecycle of the app writing to it

I disagree, we have more than one app writing to the statsd exporter - it's not a good idea to be restarting it frequently as many udp packets will be lost while it's coming back up.
